DROP SCHEMA IF EXISTS DAT108_OBLIG4 CASCADE;
CREATE SCHEMA DAT108_OBLIG4;
SET search_path TO DAT108_OBLIG4;

CREATE TABLE deltager
(
    mobil     CHARACTER(8) PRIMARY KEY,
    hash      CHARACTER(64) NOT NULL,
    salt      CHARACTER(32) NOT NULL,
    fornavn   CHARACTER VARYING(40),
    etternavn CHARACTER VARYING(40),
    kjonn     CHARACTER VARYING(6)
);